### ISSUE TITLE
Spec tests are failing due to facter version, Gitlab jobs are failing for the same reason

### ISSUE THREAD

**Issue by rgardner4012** [simp/pupmod-simp-mockup#85]
An error occurred while loading ./spec/classes/init_spec.rb.
Failure/Error:
      on_supported_os.each do |os, os_facts|
        context "on #{os}" do
          let(:facts) do
            os_facts
          end
  
          context "dummy class without any parameters" do
            let(:params) {{ }}
            it_behaves_like "a structured module"
            it { is_expected.to contain_class('dummy').with_trusted_nets(['127.0.0.1/32']) }

RuntimeError:
  Can't find SIMP facts for Facter 4.3, skipping...

  HINT: If this version of Facter has been released recently, try running

      `FACTER_GEM_VERSION='~> X.Y.0' bundler update facter

  Where 'X.Y' is the version of the last facter that worked
# ./spec/classes/init_spec.rb:17:in `block (2 levels) in <top (required)>'
# ./spec/classes/init_spec.rb:16:in `block in <top (required)>'
# ./spec/classes/init_spec.rb:3:in `<top (required)>'
No examples found.

Finished in 0.00004 seconds (files took 1.14 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples

/opt/hostedtoolcache/Ruby/2.7.7/x64/bin/ruby -I/home/runner/work/pupmod-simp-mockup/pupmod-simp-mockup/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.12.1/lib:/home/runner/work/pupmod-simp-mockup/pupmod-simp-mockup/vendor/bundle/ruby/2.7.0/gems/rspec-support-3.12.0/lib /home/runner/work/pupmod-simp-mockup/pupmod-simp-mockup/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.12.1/exe/rspec --pattern spec/\{aliases,classes,defines,functions,hosts,integration,plans,tasks,type_aliases,types,unit\}/\*\*/\*_spec.rb failed

**Comment by AndyAdrian-OP** [comment]
fixed by https://github.com/simp/rubygem-simp-rspec-puppet-facts/pull/47
